/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiDebugRouteImport } from './routes/api.debug'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiWebhooksJiraRouteImport } from './routes/api.webhooks.jira'
import { Route as ApiNotificationsSendRouteImport } from './routes/api.notifications.send'
import { Route as ApiJiraUpdateSlaRouteImport } from './routes/api.jira.update-sla'
import { Route as ApiJiraSearchRouteImport } from './routes/api.jira.search'
import { Route as ApiEventsStreamRouteImport } from './routes/api.events.stream'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiJiraIssueIssueKeyChangelogRouteImport } from './routes/api.jira.issue.$issueKey.changelog'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRoute = ApiDebugRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksJiraRoute = ApiWebhooksJiraRouteImport.update({
  id: '/api/webhooks/jira',
  path: '/api/webhooks/jira',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsSendRoute = ApiNotificationsSendRouteImport.update({
  id: '/api/notifications/send',
  path: '/api/notifications/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJiraUpdateSlaRoute = ApiJiraUpdateSlaRouteImport.update({
  id: '/api/jira/update-sla',
  path: '/api/jira/update-sla',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJiraSearchRoute = ApiJiraSearchRouteImport.update({
  id: '/api/jira/search',
  path: '/api/jira/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsStreamRoute = ApiEventsStreamRouteImport.update({
  id: '/api/events/stream',
  path: '/api/events/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJiraIssueIssueKeyChangelogRoute =
  ApiJiraIssueIssueKeyChangelogRouteImport.update({
    id: '/api/jira/issue/$issueKey/changelog',
    path: '/api/jira/issue/$issueKey/changelog',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/issues': typeof IssuesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/health': typeof ApiHealthRoute
  '/api/events/stream': typeof ApiEventsStreamRoute
  '/api/jira/search': typeof ApiJiraSearchRoute
  '/api/jira/update-sla': typeof ApiJiraUpdateSlaRoute
  '/api/notifications/send': typeof ApiNotificationsSendRoute
  '/api/webhooks/jira': typeof ApiWebhooksJiraRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/jira/issue/$issueKey/changelog': typeof ApiJiraIssueIssueKeyChangelogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/issues': typeof IssuesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/health': typeof ApiHealthRoute
  '/api/events/stream': typeof ApiEventsStreamRoute
  '/api/jira/search': typeof ApiJiraSearchRoute
  '/api/jira/update-sla': typeof ApiJiraUpdateSlaRoute
  '/api/notifications/send': typeof ApiNotificationsSendRoute
  '/api/webhooks/jira': typeof ApiWebhooksJiraRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/jira/issue/$issueKey/changelog': typeof ApiJiraIssueIssueKeyChangelogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/issues': typeof IssuesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/health': typeof ApiHealthRoute
  '/api/events/stream': typeof ApiEventsStreamRoute
  '/api/jira/search': typeof ApiJiraSearchRoute
  '/api/jira/update-sla': typeof ApiJiraUpdateSlaRoute
  '/api/notifications/send': typeof ApiNotificationsSendRoute
  '/api/webhooks/jira': typeof ApiWebhooksJiraRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/jira/issue/$issueKey/changelog': typeof ApiJiraIssueIssueKeyChangelogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/developers'
    | '/issues'
    | '/reports'
    | '/settings'
    | '/api/debug'
    | '/api/health'
    | '/api/events/stream'
    | '/api/jira/search'
    | '/api/jira/update-sla'
    | '/api/notifications/send'
    | '/api/webhooks/jira'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/jira/issue/$issueKey/changelog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/developers'
    | '/issues'
    | '/reports'
    | '/settings'
    | '/api/debug'
    | '/api/health'
    | '/api/events/stream'
    | '/api/jira/search'
    | '/api/jira/update-sla'
    | '/api/notifications/send'
    | '/api/webhooks/jira'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/jira/issue/$issueKey/changelog'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/developers'
    | '/issues'
    | '/reports'
    | '/settings'
    | '/api/debug'
    | '/api/health'
    | '/api/events/stream'
    | '/api/jira/search'
    | '/api/jira/update-sla'
    | '/api/notifications/send'
    | '/api/webhooks/jira'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/jira/issue/$issueKey/changelog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  IssuesRoute: typeof IssuesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiDebugRoute: typeof ApiDebugRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiEventsStreamRoute: typeof ApiEventsStreamRoute
  ApiJiraSearchRoute: typeof ApiJiraSearchRoute
  ApiJiraUpdateSlaRoute: typeof ApiJiraUpdateSlaRoute
  ApiNotificationsSendRoute: typeof ApiNotificationsSendRoute
  ApiWebhooksJiraRoute: typeof ApiWebhooksJiraRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  ApiJiraIssueIssueKeyChangelogRoute: typeof ApiJiraIssueIssueKeyChangelogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/jira': {
      id: '/api/webhooks/jira'
      path: '/api/webhooks/jira'
      fullPath: '/api/webhooks/jira'
      preLoaderRoute: typeof ApiWebhooksJiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/send': {
      id: '/api/notifications/send'
      path: '/api/notifications/send'
      fullPath: '/api/notifications/send'
      preLoaderRoute: typeof ApiNotificationsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jira/update-sla': {
      id: '/api/jira/update-sla'
      path: '/api/jira/update-sla'
      fullPath: '/api/jira/update-sla'
      preLoaderRoute: typeof ApiJiraUpdateSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jira/search': {
      id: '/api/jira/search'
      path: '/api/jira/search'
      fullPath: '/api/jira/search'
      preLoaderRoute: typeof ApiJiraSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/stream': {
      id: '/api/events/stream'
      path: '/api/events/stream'
      fullPath: '/api/events/stream'
      preLoaderRoute: typeof ApiEventsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jira/issue/$issueKey/changelog': {
      id: '/api/jira/issue/$issueKey/changelog'
      path: '/api/jira/issue/$issueKey/changelog'
      fullPath: '/api/jira/issue/$issueKey/changelog'
      preLoaderRoute: typeof ApiJiraIssueIssueKeyChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  IssuesRoute: IssuesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiDebugRoute: ApiDebugRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiEventsStreamRoute: ApiEventsStreamRoute,
  ApiJiraSearchRoute: ApiJiraSearchRoute,
  ApiJiraUpdateSlaRoute: ApiJiraUpdateSlaRoute,
  ApiNotificationsSendRoute: ApiNotificationsSendRoute,
  ApiWebhooksJiraRoute: ApiWebhooksJiraRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  ApiJiraIssueIssueKeyChangelogRoute: ApiJiraIssueIssueKeyChangelogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
